clear;clc;close all;
load('degeneracy.mat');%generated by "c210501_1_TFnormal_degenercy_make_array.m"
mus = 0:1:70;
sigmas = 10:1:60;
bin_centers = 2.5:5:177.5;

mu=0;
sigma=20;

i_mu=find(mus==mu);
i_sigma=find(sigmas==sigma);

[X,Y]=meshgrid(mus,sigmas);
rmsd_matrix=zeros(length(mus),length(sigmas),1);
for i=1:length(mus)
    for j=1:length(sigmas)
        rmsd_matrix(i,j)=rmsd(i_mu,i_sigma,i,j);
    end
end

% subplot(1,2,1);
% s=surf(X,Y,rmsd_matrix','FaceAlpha',0.5);
% ax = gca;
% % ax.CLim=([0,0.0005]);
% view([90,90]);%camera angle
% xlabel('\mu (degrees)','FontSize',15);
% ylabel('\sigma (degrees)','FontSize',15);
% ylim([10,60]);
% xlim([0,70]);
% set(gca,'FontSize',15);
% set(gca,'Xdir','reverse');
% pbaspect([1 1 1]);%aspect ratio
% colormap hot
% colorbar('Location','northoutside')

subplot(1,2,1);
s=surf(Y,X,rmsd_matrix','FaceAlpha',0.5);
ax = gca;
ax.CLim=([0,0.015]);
view([90,90]);%camera angle
ylabel('\mu (degrees)','FontSize',15);
xlabel('\sigma (degrees)','FontSize',15);
xlim([10,60]);
ylim([0,70]);
set(gca,'FontSize',15);
set(gca,'Xdir','reverse');
pbaspect([1 1 1]);%aspect ratio
colorbar('Location','northoutside')

subplot(1,2,2);
s=surf(Y,X,rmsd_matrix','FaceAlpha',0.5);
ax = gca;
ax.CLim=([0,0.0005]);
view([90,90]);%camera angle
ylabel('\mu (degrees)','FontSize',15);
xlabel('\sigma (degrees)','FontSize',15);
xlim([10,60]);
ylim([0,70]);
set(gca,'FontSize',15);
set(gca,'Xdir','reverse');
pbaspect([1 1 1]);%aspect ratio
colorbar('Location','northoutside')
colormap hot

set(gcf,'units','normalized');%for fitting the generated figure to the size of screen
set(gcf,'outerposition',[0 0 1 1]);